### ISSUE TITLE
[bug] ABOD / KNN / LUNAR / SOD raise TypeError on any kwarg sklearn's NearestNeighbors doesn't accept (e.g. random_state)

### ISSUE THREAD

**Issue by yzhao062** [yzhao062/pyod#685]
## Summary

Four detectors — `ABOD`, `KNN`, `LUNAR`, `SOD` — accept arbitrary `**kwargs`
in `__init__` and forward them unfiltered to `sklearn.neighbors.NearestNeighbors`.
Any kwarg that `NearestNeighbors.__init__` does not accept (e.g. `random_state`,
`verbose`, `cache_size`, any typo) raises `TypeError` at fit/init time.

This was introduced in commit b8f6c81 ("fix issue #654 for consistent sklearn's
NearestNeighbors usage", 2026-02-26), which over-forwards kwargs while
implementing the intended exposure of `algorithm`, `n_neighbors`, `n_jobs`, etc.

## Reproducer

```python
import numpy as np
X = np.random.RandomState(42).randn(200, 5)

from pyod.models.abod  import ABOD
from pyod.models.knn   import KNN
from pyod.models.lunar import LUNAR
from pyod.models.sod   import SOD

for cls in (ABOD, KNN, LUNAR, SOD):
    try:
        cls(random_state=42).fit(X)
        print(f"{cls.__name__}: OK")
    except TypeError as e:
        print(f"{cls.__name__}: {e}")
```

Output (pyod 3.5.1):

```
ABOD: NearestNeighbors.__init__() got an unexpected keyword argument 'random_state'
KNN: NearestNeighbors.__init__() got an unexpected keyword argument 'random_state'
LUNAR: NearestNeighbors.__init__() got an unexpected keyword argument 'random_state'
SOD: NearestNeighbors.__init__() got an unexpected keyword argument 'random_state'
```

Any kwarg that `NearestNeighbors` does not accept reproduces the same TypeError:

```python
ABOD(verbose=1).fit(X)       # TypeError: ... 'verbose'
ABOD(cache_size=100).fit(X)  # TypeError: ... 'cache_size'
ABOD(unknown_arg=1).fit(X)   # TypeError: ... 'unknown_arg'
```

## Root cause

- `pyod/models/abod.py:166`  — `__init__(..., **kwargs)`; `self.kwargs = kwargs` at L176; `NearestNeighbors(..., **self.kwargs)` at L251.
- `pyod/models/knn.py:144`   — `__init__(..., **kwargs)`; `NearestNeighbors(..., **kwargs)` at L161-169 (direct, no `self.kwargs` storage).
- `pyod/models/lunar.py`     — same pattern; `NearestNeighbors(..., **self.kwargs)` at L307-314.
- `pyod/models/sod.py`       — same pattern; `NearestNeighbors(..., **self.kwargs)` at L198-205.

`sklearn.neighbors.NearestNeighbors` (sklearn 1.8.0) does not accept
`random_state`, `verbose`, `cache_size`, or any kwarg outside its documented
signature. The unfiltered `**kwargs` forward causes `TypeError`.

## Impact

1. **Common idiom broken.** `Detector(random_state=42)` is the standard sklearn
   reproducibility pattern. Users who reach for it on these four detectors hit
   the TypeError immediately. PyOD documentation and notebooks recommend this
   idiom in several places.
2. **ADEngine routing surface.** `ADEngine.plan_detection` can route to any of
   the four affected detectors. Once the routing layer or an external agent
   passes any non-NearestNeighbors kwarg to the resolved class, the whole
   investigation fails.
3. **Typos crash silently late.** Any unknown kwarg (e.g. `n_neighbours=5` —
   British spelling typo) crashes at fit time with a stack trace pointing into
   sklearn, not into the pyod call site that mistyped.

Observed while running §5 evidence for the PyOD 3 paper (KDD 2027 ADS Cycle 1):
the substrate-on/off agent reproducibility experiment had to denylist all four
detectors because the agent's default reproducibility prompt sets `random_state`.

## Environment

- pyod: 3.5.1 (git `e862d1d`, development branch)
- sklearn: 1.8.0
- numpy: 2.4.4
- Python: 3.12.12
- OS: Windows 11 (also reproduces on Linux py312)

## Suggested fix

Three options, in order of preference:

**(A) Remove `**kwargs` from `__init__`. Explicit-list the forwarded params.**
Cleanest. The named params added in b8f6c81 (`algorithm`, `leaf_size`, `metric`,
`p`, `metric_params`, `n_jobs`) already cover what #654 asked for. Removing the
catch-all `**kwargs` makes the constructor signature self-documenting and
prevents typo-late-crash. A user wanting future-proofing for new sklearn kwargs
can subclass.

**(B) Filter kwargs against NearestNeighbors signature before forwarding.**
Keeps the catch-all but drops anything sklearn does not accept:

```python
import inspect
from sklearn.neighbors import NearestNeighbors

_NN_PARAMS = set(inspect.signature(NearestNeighbors.__init__).parameters)
nn_kwargs = {k: v for k, v in self.kwargs.items() if k in _NN_PARAMS}
self.neigh_ = NearestNeighbors(..., **nn_kwargs)
```

Risk: silently drops user-supplied kwargs (e.g. `random_state`) without
warning. Better than crashing but worse than (A) for debuggability.

**(C) Whitelist `random_state` and drop it explicitly.**
Most surgical:

```python
nn_kwargs = {k: v for k, v in self.kwargs.items() if k != 'random_state'}
```

This matches the actual symptom but does not fix the typo case.

I recommend (A). Happy to send a PR if useful.

## Files to change

- `pyod/models/abod.py`
- `pyod/models/knn.py`
- `pyod/models/lunar.py`
- `pyod/models/sod.py`
- corresponding `pyod/test/test_*.py` — add a test that `Detector(random_state=42)` does not raise.
