### ISSUE TITLE
TypeError: SUOD.__init__() got an unexpected keyword argument 'cost_forecast_loc_fit'

### ISSUE THREAD

**Issue by jajinkya** [yzhao062/pyod#545]
I was trying to use SUOD model from pyod model list. Initially when importing SUOD ; throwing error of module not found. So I have installed SUOD with command `! pip install --pre suod `. Then I was getting error of `SUOD.__init__() got an unexpected keyword argument 'cost_forecast_loc_fit'`.

![image](https://github.com/yzhao062/pyod/assets/42177213/ef5988b1-5c5c-41ed-9a1d-a7bbc93db367)

**Comment by yzhao062** [comment]
Please try to update pyod to 1.1.3. I just release this version

**Comment by jajinkya** [comment]
It is resolved after updating the pyod library to 1.1.3. Thanks

**Comment by owgreen-dev** [comment]
On current master (v3.6.6) the wrapper no longer passes `cost_forecast_loc_fit` (there is no occurrence of that name in `pyod/models/suod.py`), and a default `SUOD().fit(X)` works with `suod` from PyPI:

```python
from pyod.models.suod import SUOD
SUOD(n_jobs=1, verbose=False).fit(X).decision_scores_.shape   # (200,)
```

For anyone hitting this on 2.0.5, upgrading pyod resolves it. Suggest closing.
